######################################################################
# VTK Designer 2 - VTKSystem component
# 
# Provides several VTK Classes
######################################################################

include(../../GCF/qmake_prf/gcf_component.prf)
include(../../VTK.pri)

DESTDIR = ../../bin
DEPENDPATH += . interfaces source
INCLUDEPATH += . interfaces source ../../Interfaces ../../Common

DEPENDPATH      += . \
                   Interfaces \
                   IOData \
                   ControlData \
                   ScriptableDataObjects \
                   Wrappers \
                   VCLClasses \
                   Wrappers/Common \
                   Wrappers/Source \
                   Wrappers/Mapper \
                   Wrappers/Rendering \
                   Wrappers/Filters \
                   Wrappers/Custom \
                   Wrappers/Functions \
                   Wrappers/Widgets 

INCLUDEPATH     += . \
                   Interfaces \
                   IOData \
                   ControlData \
                   ScriptableDataObjects \
                   VCLClasses \
                   Wrappers \
                   Wrappers/Common \
                   Wrappers/Source \
                   Wrappers/Mapper \
                   Wrappers/Rendering \
                   Wrappers/Filters \
                   Wrappers/Custom \
                   Wrappers/Functions \
                   Wrappers/Widgets 

# Input
HEADERS += CVtkObject.h \
           CVtkObjectConnectionPath.h \
           CVtkObjectDesc.h \
           CVtkVisSystemComponent.h \
           CVtkTimerObject.h \
           CVtkMath.h \
           CPipelineProgressMonitor.h \
           ScriptableDataObjects/CScriptableVtkDataObject.h \
           ScriptableDataObjects/CScriptableVtkDataSet.h \
           ScriptableDataObjects/CScriptableVtkPointSet.h \
           ScriptableDataObjects/CScriptableVtkPolyData.h \
           ScriptableDataObjects/CScriptableVtkImageData.h \
           VCLClasses/vtkFlythroughCamera.h \
           VCLClasses/vtkCenterlineFilter.h \
           VCLClasses/vtkImageToTerrain.h \
           VCLClasses/vtkBezierSurfaceSource.h \
           VCLClasses/vtkBezierSurfaceWidget.h \
           VCLClasses/vtkWedgeSource.h \
           Wrappers/Custom/CVtkCustomPolyDataSource.h \
           Wrappers/Custom/CVtkCustomGridPolyDataSource.h \
           Wrappers/Custom/CVtkCustomPolyDataFilter.h \
           Wrappers/Custom/CVtkCustomFunction.h \
           Wrappers/Custom/CVtkCustomImageSource.h \
           Wrappers/Custom/CVtkCustomUnstructuredGridSource.h \
           Wrappers/Common/CVtkAlgorithm.h \
           Wrappers/Common/CVtkPolyDataAlgorithm.h \
           Wrappers/Common/CVtkImageAlgorithm.h \
           Wrappers/Common/CVtkThreadedImageAlgorithm.h \
           Wrappers/Common/CVtkImageReader2.h \
           Wrappers/Common/CVtkTexture.h \
           Wrappers/Common/CVtkImageReader.h \
           Wrappers/Common/CVtkPolyDataFilter.h \
           Wrappers/Common/CVtkDataSetAlgorithm.h \
           Wrappers/Common/CVtkDataSetFilter.h \
           Wrappers/Common/CVtkUnstructuredGridAlgorithm.h \
           Wrappers/Common/CVtkPointSetAlgorithm.h \
           Wrappers/Common/CVtkPointSetFilter.h \
           Wrappers/Common/CVtkScalarsToColors.h \
           Wrappers/Common/CVtkColorTransferFunction.h \
           Wrappers/Common/CVtkLookupTable.h \
           Wrappers/Common/CVtkPiecewiseFunction.h \
           Wrappers/Common/CVtkAbstractTransform.h \
           Wrappers/Common/CVtkTransform.h \
           Wrappers/Common/CVtkImporter.h \
           Wrappers/Common/CVtk3DSImporter.h \
           Wrappers/Common/CVtkVRMLImporter.h \
           Wrappers/Common/CVtkInteractorObserver.h \
           Wrappers/Source/CVtkConeSource.h \
           Wrappers/Source/CVtkSphereSource.h \
           Wrappers/Source/CVtkArrowSource.h \
           Wrappers/Source/CVtkCubeSource.h \
           Wrappers/Source/CVtkCylinderSource.h \
           Wrappers/Source/CVtkLineSource.h \
           Wrappers/Source/CVtkPlaneSource.h \
           Wrappers/Source/CVtkPointSource.h \
           Wrappers/Source/CVtkTextSource.h \
           Wrappers/Source/CVtkDiskSource.h \
           Wrappers/Source/CVtkVectorText.h \
           Wrappers/Source/CVtkAxes.h \
           Wrappers/Source/CVtkCursor3D.h \
           Wrappers/Source/CVtkJPEGReader.h \
           Wrappers/Source/CVtkPNGReader.h \
           Wrappers/Source/CVtkSLCReader.h \
           Wrappers/Source/CVtkTIFFReader.h \
           Wrappers/Source/CVtkBMPReader.h \
           Wrappers/Source/CVtkPNMReader.h \ 
           Wrappers/Source/CVtkRegularPolygonSource.h \    
           Wrappers/Source/CVtkSimplePointsReader.h \
           Wrappers/Source/CVtkSuperquadricSource.h \
           Wrappers/Source/CVtkTexturedSphereSource.h \
           Wrappers/Source/CVtkEarthSource.h \ 
           Wrappers/Source/CVtkPLYReader.h \
           Wrappers/Source/CVtkPlatonicSolidSource.h \ 
           Wrappers/Source/CVtkFacetReader.h \
           Wrappers/Source/CVtkParticleReader.h \
           Wrappers/Source/CVtkSampleFunction.h \
           Wrappers/Source/CVtkAbstractPropPicker.h \
           Wrappers/Source/CVtkPicker.h \
           Wrappers/Source/CVtkCellPicker.h \
           Wrappers/Source/CVtkPointPicker.h \
           Wrappers/Source/CVtkPropPicker.h \           
           Wrappers/Source/CVtkStructuredGridSource.h \
           Wrappers/Source/CVtkDICOMImageReader.h \
           Wrappers/Source/CVtkPLOT3DReader.h \
           Wrappers/Source/CVtkDEMReader.h \
           Wrappers/Source/CVtkMoleculeReaderBase.h \
           Wrappers/Source/CVtkGaussianCubeReader.h \
           Wrappers/Source/CVtkPDBReader.h \
           Wrappers/Source/CVtkXYZMolReader.h \
           Wrappers/Source/CVtkDataReader.h \
           Wrappers/Source/CVtkDataObjectReader.h \
           Wrappers/Source/CVtkDataSetReader.h \
           Wrappers/Source/CVtkPolyDataReader.h \
           Wrappers/Source/CVtkRectilinearGridReader.h \
           Wrappers/Source/CVtkStructuredGridReader.h \
           Wrappers/Source/CVtkUnstructuredGridReader.h \
           Wrappers/Source/CVtkStructuredPointsReader.h \
           Wrappers/Source/CVtkBYUReader.h \
           Wrappers/Source/CVtkImageToTerrain.h \
           Wrappers/Source/CVtkBezierSurfaceSource.h \
           Wrappers/Source/CVtkWedgeSource.h \
           Wrappers/Mapper/CVtkPolyDataMapper.h \
           Wrappers/Mapper/CVtkDataSetMapper.h \
           Wrappers/Rendering/CVtkProp3D.h \
           Wrappers/Rendering/CVtkActor.h \
           Wrappers/Rendering/CVtkAssembly.h \
           Wrappers/Rendering/CVtkRenderer.h \
           Wrappers/Rendering/CVtkRenderWindow.h \
           Wrappers/Rendering/CVtkCamera.h \
           Wrappers/Rendering/CVtkFlythroughCamera.h \
           Wrappers/Rendering/CVtkProperty.h \
           Wrappers/Rendering/CVtkLocator.h \
           Wrappers/Rendering/CVtkCellLocator.h \
           Wrappers/Rendering/CVtkPointLocator.h \
           Wrappers/Rendering/CVtkAbstractPicker.h \
           Wrappers/Rendering/CVtkActor2D.h \
           Wrappers/Rendering/CVtkMapper2D.h \
           Wrappers/Rendering/CVtkImageMapper.h \
           Wrappers/Rendering/CVtkAxisActor2D.h \
           Wrappers/Filters/CVtkLinearExtrusionFilter.h \
           Wrappers/Filters/CVtkPolyDataNormals.h \
           Wrappers/Filters/CVtkTriangleFilter.h \
           Wrappers/Filters/CVtkContourFilter.h \
           Wrappers/Filters/CVtkBandedPolyDataContourFilter.h \
           Wrappers/Filters/CVtkTubeFilter.h  \
           Wrappers/Filters/CVtkDataSetSurfaceFilter.h \
           Wrappers/Filters/CVtkExtractEdges.h \
           Wrappers/Filters/CVtkExtractPolyDataGeometry.h   \
           Wrappers/Filters/CVtkTransformPolyDataFilter.h \
           Wrappers/Filters/CVtkShrinkPolyData.h \
           Wrappers/Filters/CVtkOutlineCornerFilter.h \
           Wrappers/Filters/CVtkOutlineFilter.h \
           Wrappers/Filters/CVtkGenericOutlineFilter.h \
           Wrappers/Filters/CVtkContourGrid.h \
           Wrappers/Filters/CVtkGenericContourFilter.h \
           Wrappers/Filters/CVtkRibbonFilter.h \
           Wrappers/Filters/CVtkGeometryFilter.h \
           Wrappers/Filters/CVtkFeatureEdges.h \
           Wrappers/Filters/CVtkMarchingContourFilter.h \           
           Wrappers/Filters/CVtkMarchingSquares.h \
           Wrappers/Filters/CVtkGraphLayoutFilter.h \
           Wrappers/Filters/CVtkEdgePoints.h \
           Wrappers/Filters/CVtkHedgeHog.h \
           Wrappers/Filters/CVtkMaskPolyData.h \
           Wrappers/Filters/CVtkPolyDataStreamer.h \
           Wrappers/Filters/CVtkRuledSurfaceFilter.h \
           Wrappers/Filters/CVtkHyperStreamLine.h \
           Wrappers/Filters/CVtkImageToPolyDataFilter.h \
           Wrappers/Filters/CVtkPolyDataConnectivityFilter.h \
           Wrappers/Filters/CVtkRotationalExtrusionFilter.h \
           Wrappers/Filters/CVtkHierarchicalDataSetGeometryFilter.h \
           Wrappers/Filters/CVtkGreedyTerrainDecimation.h \
           Wrappers/Filters/CVtkGridSynchronizedTemplates3D.h \
           Wrappers/Filters/CVtkDecimatePro.h \
           Wrappers/Filters/CVtkDelaunay2D.h \
           Wrappers/Filters/CVtkElevationFilter.h \
           Wrappers/Filters/CVtkCurvatures.h \
           Wrappers/Filters/CVtkCutter.h \
           Wrappers/Filters/CVtkGenericCutter.h \
           Wrappers/Filters/CVtkSmoothPolyDataFilter.h \
           Wrappers/Filters/CVtkDepthSortPolyData.h \
           Wrappers/Filters/CVtkProjectedTerrainPath.h \
           Wrappers/Filters/CVtkGlyph3D.h \
           Wrappers/Filters/CVtkCenterlineFilter.h \
           Wrappers/Filters/CVtkBrownianPoints.h \
           Wrappers/Filters/CVtkProjectedTexture.h \
           Wrappers/Filters/CVtkSimpleElevationFilter.h \
           Wrappers/Filters/CVtkTextureMapToCylinder.h \
           Wrappers/Filters/CVtkTextureMapToPlane.h \
           Wrappers/Filters/CVtkTextureMapToSphere.h \
           Wrappers/Filters/CVtkTransformFilter.h \
           Wrappers/Filters/CVtkWarpLens.h \
           Wrappers/Filters/CVtkWarpScalar.h \
           Wrappers/Filters/CVtkWarpTo.h \
           Wrappers/Filters/CVtkWarpVector.h \
           Wrappers/Filters/CVtkWeightedTransformFilter.h \
           Wrappers/Filters/CVtkClipDataSet.h \
           Wrappers/Filters/CVtkClipPolyData.h \
           Wrappers/Filters/CVtkSplineFilter.h \
           Wrappers/Filters/CVtkStreamer.h \
           Wrappers/Filters/CVtkStreamLine.h \
           Wrappers/Filters/CVtkDashedStreamLine.h \
           Wrappers/Filters/CVtkStreamPoints.h \
           Wrappers/Filters/CVtkStripper.h \
           Wrappers/Filters/CVtkAppendPolyData.h \
           Wrappers/Filters/CVtkCellCenters.h \
           Wrappers/Filters/CVtkCleanPolyData.h \
#           Wrappers/Filters/CVtkDuplicatePolyData.h \
           Wrappers/Filters/CVtkGenericGeometryFilter.h \
           Wrappers/Filters/CVtkGenericGlyph3DFilter.h \
           Wrappers/Filters/CVtkGenericStreamTracer.h \
#           Wrappers/Filters/CVtkStreamTracer.h \
           Wrappers/Filters/CVtkLoopSubdivisionFilter.h \
           Wrappers/Filters/CVtkInterpolatingSubdivisionFilter.h \
           Wrappers/Filters/CVtkButterflySubdivisionFilter.h \
           Wrappers/Filters/CVtkLinearSubdivisionFilter.h \
           Wrappers/Filters/CVtkStructuredGridGeometryFilter.h \
           Wrappers/Filters/CVtkStructuredGridOutlineFilter.h \
           Wrappers/Filters/CVtkGaussianSplatter.h \
           Wrappers/Filters/CVtkImageLuminance.h \
           Wrappers/Filters/CVtkImageDataGeometryFilter.h \
           Wrappers/Filters/CVtkMergeFilter.h \
           Wrappers/Filters/CVtkProbeFilter.h \
           Wrappers/Filters/CVtkImageReslice.h \
           Wrappers/Filters/CVtkImageMapToColors.h \
           Wrappers/Filters/CVtkImageMapToWindowLevelColors.h \
           Wrappers/Functions/CVtkImplicitFunction.h \          
           Wrappers/Functions/CVtkBox.h \
           Wrappers/Functions/CVtkCone.h \
           Wrappers/Functions/CVtkCylinder.h \ 
           Wrappers/Functions/CVtkPlane.h \
           Wrappers/Functions/CVtkQuadric.h \
           Wrappers/Functions/CVtkSphere.h \
           Wrappers/Functions/CVtkSuperquadric.h \
           Wrappers/Functions/CVtkImplicitBoolean.h \
           Wrappers/Source/CVtkVolume16Reader.h \
           Wrappers/Source/CVtkVolumeReader.h \
           Wrappers/Widgets/CVtk3DWidget.h \
           Wrappers/Widgets/CVtkBoxWidget.h \
           # Wrappers/Widgets/CVtkLineWidget.h \
           Wrappers/Widgets/CVtkSphereWidget.h \
           Wrappers/Widgets/CVtkSplineWidget.h \
           Wrappers/Widgets/CVtkPointWidget.h \
           Wrappers/Widgets/CVtkPolyDataSourceWidget.h \
           Wrappers/Widgets/CVtkBezierSurfaceWidget.h \
    Wrappers/Source/CVtkSTLReader.h
                      
           
SOURCES += CVtkObject.cpp \
           CVtkObjectDesc.cpp \
           CVtkVisSystemComponent.cpp \
           CVtkTimerObject.cpp \
           CVtkMath.cpp \
           CPipelineProgressMonitor.cpp \
           ScriptableDataObjects/CScriptableVtkDataObject.cpp \
           ScriptableDataObjects/CScriptableVtkDataSet.cpp \
           ScriptableDataObjects/CScriptableVtkPointSet.cpp \
           ScriptableDataObjects/CScriptableVtkPolyData.cpp \
           ScriptableDataObjects/CScriptableVtkImageData.cpp \
           VCLClasses/vtkFlythroughCamera.cpp \
           VCLClasses/vtkCenterlineFilter.cpp \
           VCLClasses/vtkImageToTerrain.cpp \
           VCLClasses/vtkBezierSurfaceSource.cpp \
           VCLClasses/vtkBezierSurfaceWidget.cpp \
           VCLClasses/vtkWedgeSource.cpp \
           Wrappers/Custom/CVtkCustomPolyDataSource.cpp \
           Wrappers/Custom/CVtkCustomGridPolyDataSource.cpp \
           Wrappers/Custom/CVtkCustomUnstructuredGridSource.cpp \
           Wrappers/Custom/CVtkCustomPolyDataFilter.cpp \
           Wrappers/Custom/CVtkCustomFunction.cpp \
           Wrappers/Custom/CVtkCustomImageSource.cpp \
           Wrappers/Common/CVtkAlgorithm.cpp \
           Wrappers/Common/CVtkPolyDataAlgorithm.cpp \
           Wrappers/Common/CVtkImageAlgorithm.cpp \
           Wrappers/Common/CVtkThreadedImageAlgorithm.cpp \
           Wrappers/Common/CVtkImageReader2.cpp \
           Wrappers/Common/CVtkTexture.cpp \
           Wrappers/Common/CVtkImageReader.cpp \           
           Wrappers/Common/CVtkPolyDataFilter.cpp \
           Wrappers/Common/CVtkDataSetAlgorithm.cpp \
           Wrappers/Common/CVtkDataSetFilter.cpp \
           Wrappers/Common/CVtkUnstructuredGridAlgorithm.cpp \
           Wrappers/Common/CVtkPointSetAlgorithm.cpp \
           Wrappers/Common/CVtkPointSetFilter.cpp \
           Wrappers/Common/CVtkScalarsToColors.cpp \
           Wrappers/Common/CVtkColorTransferFunction.cpp \
           Wrappers/Common/CVtkLookupTable.cpp \
           Wrappers/Common/CVtkPiecewiseFunction.cpp \
           Wrappers/Common/CVtkAbstractTransform.cpp \
           Wrappers/Common/CVtkTransform.cpp \
           Wrappers/Common/CVtkImporter.cpp \
           Wrappers/Common/CVtk3DSImporter.cpp \
           Wrappers/Common/CVtkVRMLImporter.cpp \
           Wrappers/Common/CVtkInteractorObserver.cpp \
           Wrappers/Source/CVtkConeSource.cpp \
           Wrappers/Source/CVtkSphereSource.cpp \
           Wrappers/Source/CVtkArrowSource.cpp \
           Wrappers/Source/CVtkCubeSource.cpp \
           Wrappers/Source/CVtkCylinderSource.cpp \
           Wrappers/Source/CVtkLineSource.cpp \
           Wrappers/Source/CVtkPlaneSource.cpp \
           Wrappers/Source/CVtkPointSource.cpp \
           Wrappers/Source/CVtkTextSource.cpp \           
           Wrappers/Source/CVtkDiskSource.cpp \
           Wrappers/Source/CVtkVectorText.cpp \           
           Wrappers/Source/CVtkAxes.cpp \
           Wrappers/Source/CVtkCursor3D.cpp \
           Wrappers/Source/CVtkJPEGReader.cpp \
           Wrappers/Source/CVtkPNGReader.cpp \           
           Wrappers/Source/CVtkSLCReader.cpp \ 
           Wrappers/Source/CVtkTIFFReader.cpp \
           Wrappers/Source/CVtkBMPReader.cpp \
           Wrappers/Source/CVtkPNMReader.cpp \              
           Wrappers/Source/CVtkRegularPolygonSource.cpp \    
           Wrappers/Source/CVtkSimplePointsReader.cpp \ 
           Wrappers/Source/CVtkSuperquadricSource.cpp \           
           Wrappers/Source/CVtkTexturedSphereSource.cpp \        
           Wrappers/Source/CVtkEarthSource.cpp \
           Wrappers/Source/CVtkPLYReader.cpp \  
           Wrappers/Source/CVtkPlatonicSolidSource.cpp \
           Wrappers/Source/CVtkFacetReader.cpp \            
           Wrappers/Source/CVtkParticleReader.cpp \
           Wrappers/Source/CVtkSampleFunction.cpp \
           Wrappers/Source/CvtkAbstractPropPicker.cpp \
           Wrappers/Source/CVtkPicker.cpp \
           Wrappers/Source/CVtkCellPicker.cpp \
           Wrappers/Source/CVtkPointPicker.cpp \
           Wrappers/Source/CVtkPropPicker.cpp \        
           Wrappers/Source/CVtkStructuredGridSource.cpp \
           Wrappers/Source/CVtkDICOMImageReader.cpp \
           Wrappers/Source/CVtkPLOT3DReader.cpp \
           Wrappers/Source/CVtkDEMReader.cpp \
           Wrappers/Source/CVtkMoleculeReaderBase.cpp \
           Wrappers/Source/CVtkGaussianCubeReader.cpp \
           Wrappers/Source/CVtkPDBReader.cpp \
           Wrappers/Source/CVtkXYZMolReader.cpp \
           Wrappers/Source/CVtkDataReader.cpp \
           Wrappers/Source/CVtkDataObjectReader.cpp \
           Wrappers/Source/CVtkDataSetReader.cpp \
           Wrappers/Source/CVtkPolyDataReader.cpp \
           Wrappers/Source/CVtkRectilinearGridReader.cpp \
           Wrappers/Source/CVtkStructuredGridReader.cpp \
           Wrappers/Source/CVtkUnstructuredGridReader.cpp \
           Wrappers/Source/CVtkStructuredPointsReader.cpp \
           Wrappers/Source/CVtkBYUReader.cpp \
           Wrappers/Source/CVtkImageToTerrain.cpp \
           Wrappers/Source/CVtkBezierSurfaceSource.cpp \
           Wrappers/Source/CVtkWedgeSource.cpp \
           Wrappers/Mapper/CVtkPolyDataMapper.cpp \
           Wrappers/Mapper/CVtkDataSetMapper.cpp \
           Wrappers/Rendering/CVtkProp3D.cpp \
           Wrappers/Rendering/CVtkActor.cpp \
           Wrappers/Rendering/CVtkAssembly.cpp \
           Wrappers/Rendering/CVtkRenderer.cpp \
           Wrappers/Rendering/CVtkRenderWindow.cpp \
           Wrappers/Rendering/CVtkCamera.cpp \
           Wrappers/Rendering/CVtkFlythroughCamera.cpp \
           Wrappers/Rendering/CVtkProperty.cpp \
           Wrappers/Rendering/CVtkLocator.cpp \
           Wrappers/Rendering/CVtkCellLocator.cpp \
           Wrappers/Rendering/CVtkPointLocator.cpp \
           Wrappers/Rendering/CVtkAbstractPicker.cpp \
           Wrappers/Rendering/CVtkActor2D.cpp \
           Wrappers/Rendering/CVtkMapper2D.cpp \
           Wrappers/Rendering/CVtkImageMapper.cpp \
           Wrappers/Rendering/CVtkAxisActor2D.cpp \
           Wrappers/Filters/CVtkLinearExtrusionFilter.cpp \
           Wrappers/Filters/CVtkPolyDataNormals.cpp \
           Wrappers/Filters/CVtkTriangleFilter.cpp \
           Wrappers/Filters/CVtkContourFilter.cpp \
           Wrappers/Filters/CVtkBandedPolyDataContourFilter.cpp \                     
           Wrappers/Filters/CVtkTubeFilter.cpp  \
           Wrappers/Filters/CVtkDataSetSurfaceFilter.cpp \
           Wrappers/Filters/CVtkExtractEdges.cpp \
           Wrappers/Filters/CVtkExtractPolyDataGeometry.cpp \
           Wrappers/Filters/CVtkTransformPolyDataFilter.cpp \          
           Wrappers/Filters/CVtkShrinkPolyData.cpp \
           Wrappers/Filters/CVtkOutlineCornerFilter.cpp \                    
           Wrappers/Filters/CVtkOutlineFilter.cpp \
           Wrappers/Filters/CVtkGenericOutlineFilter.cpp \
           Wrappers/Filters/CVtkContourGrid.cpp \
           Wrappers/Filters/CVtkGenericContourFilter.cpp \
           Wrappers/Filters/CVtkRibbonFilter.cpp \
           Wrappers/Filters/CVtkGeometryFilter.cpp \
           Wrappers/Filters/CVtkFeatureEdges.cpp \
           Wrappers/Filters/CVtkMarchingContourFilter.cpp \
           Wrappers/Filters/CVtkMarchingSquares.cpp \
           Wrappers/Filters/CVtkGraphLayoutFilter.cpp \
           Wrappers/Filters/CVtkEdgePoints.cpp \
           Wrappers/Filters/CVtkHedgeHog.cpp \
           Wrappers/Filters/CVtkMaskPolyData.cpp \
           Wrappers/Filters/CVtkPolyDataStreamer.cpp \
           Wrappers/Filters/CVtkRuledSurfaceFilter.cpp \
           Wrappers/Filters/CVtkHyperStreamLine.cpp \
           Wrappers/Filters/CVtkImageToPolyDataFilter.cpp \
           Wrappers/Filters/CVtkPolyDataConnectivityFilter.cpp \
           Wrappers/Filters/CVtkRotationalExtrusionFilter.cpp \
           Wrappers/Filters/CVtkHierarchicalDataSetGeometryFilter.cpp \
           Wrappers/Filters/CVtkGreedyTerrainDecimation.cpp \
           Wrappers/Filters/CVtkGridSynchronizedTemplates3D.cpp \
           Wrappers/Filters/CVtkDecimatePro.cpp \
           Wrappers/Filters/CVtkDelaunay2D.cpp \
           Wrappers/Filters/CVtkElevationFilter.cpp \
           Wrappers/Filters/CVtkCurvatures.cpp  \
           Wrappers/Filters/CVtkCutter.cpp \
           Wrappers/Filters/CVtkGenericCutter.cpp \
           Wrappers/Filters/CVtkSmoothPolyDataFilter.cpp \
           Wrappers/Filters/CVtkDepthSortPolyData.cpp \
           Wrappers/Filters/CVtkProjectedTerrainPath.cpp \
           Wrappers/Filters/CVtkGlyph3D.cpp \
           Wrappers/Filters/CVtkCenterlineFilter.cpp \
           Wrappers/Filters/CVtkBrownianPoints.cpp \
           Wrappers/Filters/CVtkProjectedTexture.cpp \
           Wrappers/Filters/CVtkSimpleElevationFilter.cpp \
           Wrappers/Filters/CVtkTextureMapToCylinder.cpp \
           Wrappers/Filters/CVtkTextureMapToPlane.cpp \
           Wrappers/Filters/CVtkTextureMapToSphere.cpp \
           Wrappers/Filters/CVtkTransformFilter.cpp \
           Wrappers/Filters/CVtkWarpLens.cpp \
           Wrappers/Filters/CVtkWarpScalar.cpp \
           Wrappers/Filters/CVtkWarpTo.cpp \
           Wrappers/Filters/CVtkWarpVector.cpp \
           Wrappers/Filters/CVtkWeightedTransformFilter.cpp \
           Wrappers/Filters/CVtkClipDataSet.cpp \
           Wrappers/Filters/CVtkClipPolyData.cpp \
           Wrappers/Filters/CVtkSplineFilter.cpp \
           Wrappers/Filters/CVtkStreamer.cpp \
           Wrappers/Filters/CVtkStreamLine.cpp \
           Wrappers/Filters/CVtkDashedStreamLine.cpp \
           Wrappers/Filters/CVtkStreamPoints.cpp \
           Wrappers/Filters/CVtkStripper.cpp \
           Wrappers/Filters/CVtkAppendPolyData.cpp \
           Wrappers/Filters/CVtkCellCenters.cpp \
           Wrappers/Filters/CVtkCleanPolyData.cpp \
#           Wrappers/Filters/CVtkDuplicatePolyData.cpp \
           Wrappers/Filters/CVtkGenericGeometryFilter.cpp \
           Wrappers/Filters/CVtkGenericGlyph3DFilter.cpp \
           Wrappers/Filters/CVtkGenericStreamTracer.cpp \
#           Wrappers/Filters/CVtkStreamTracer.cpp \
           Wrappers/Filters/CVtkLoopSubdivisionFilter.cpp \
           Wrappers/Filters/CVtkInterpolatingSubdivisionFilter.cpp \
           Wrappers/Filters/CVtkButterflySubdivisionFilter.cpp \
           Wrappers/Filters/CVtkLinearSubdivisionFilter.cpp \
           Wrappers/Filters/CVtkStructuredGridGeometryFilter.cpp \
           Wrappers/Filters/CVtkStructuredGridOutlineFilter.cpp \ 
           Wrappers/Filters/CVtkGaussianSplatter.cpp \
           Wrappers/Filters/CVtkImageLuminance.cpp \
           Wrappers/Filters/CVtkImageDataGeometryFilter.cpp \
           Wrappers/Filters/CVtkMergeFilter.cpp \
           Wrappers/Filters/CVtkProbeFilter.cpp \    
           Wrappers/Filters/CVtkImageReslice.cpp \
           Wrappers/Filters/CVtkImageMapToColors.cpp \
           Wrappers/Filters/CVtkImageMapToWindowLevelColors.cpp \
           Wrappers/Functions/CVtkImplicitFunction.cpp \
           Wrappers/Functions/CVtkBox.cpp \
           Wrappers/Functions/CVtkCone.cpp \
           Wrappers/Functions/CVtkCylinder.cpp \           
           Wrappers/Functions/CVtkPlane.cpp \
           Wrappers/Functions/CVtkQuadric.cpp \
           Wrappers/Functions/CVtkSphere.cpp \
           Wrappers/Functions/CVtkSuperquadric.cpp \
           Wrappers/Functions/CVtkImplicitBoolean.cpp \
           Wrappers/Source/CVtkVolume16Reader.cpp \
           Wrappers/Source/CVtkVolumeReader.cpp \
           Wrappers/Widgets/CVtk3DWidget.cpp \
           Wrappers/Widgets/CVtkBoxWidget.cpp \
           # Wrappers/Widgets/CVtkLineWidget.cpp \
           Wrappers/Widgets/CVtkSphereWidget.cpp \
           Wrappers/Widgets/CVtkSplineWidget.cpp \
           Wrappers/Widgets/CVtkPointWidget.cpp \
           Wrappers/Widgets/CVtkPolyDataSourceWidget.cpp \
           Wrappers/Widgets/CVtkBezierSurfaceWidget.cpp \
    Wrappers/Source/CVtkSTLReader.cpp
           
# Input
HEADERS += IOData/CVtk3DWidgetData.h \
           IOData/CVtkAbstractMapper3DData.h \
           IOData/CVtkAbstractMapperData.h \
           IOData/CVtkActorData.h \
           IOData/CVtkDataObject.h \
           IOData/CVtkDataSet.h \
           IOData/CVtkDataSetMapperData.h \
           IOData/CVtkImageData.h \
           IOData/CVtkLookupTableData.h \
           IOData/CVtkMapperData.h \
           IOData/CVtkPiecewiseFunctionData.h \
           IOData/CVtkPointSet.h \
           IOData/CVtkPolyData.h \
           IOData/CVtkPolyDataMapperData.h \
           IOData/CVtkRectilinearGrid.h \
           IOData/CVtkRendererData.h \
           IOData/CVtkRenderWindowData.h \
           IOData/CVtkScalarsToColorsData.h \
           IOData/CVtkStructuredGrid.h \
           IOData/CVtkStructuredPoints.h \
           IOData/CVtkTextureData.h \
           IOData/CVtkUniformGrid.h \
           IOData/CVtkUnstructuredGrid.h \
           IOData/CVtkObjectIOData.h \
           IOData/CVtkProp3DData.h \
           IOData/CVtkCameraData.h \
           IOData/CVtkImplicitFunctionData.h \
           IOData/CVtkPropertyData.h \
           ControlData/CVtkObjectControlData.h 

SOURCES += IOData/CVtk3DWidgetData.cpp \
           IOData/CVtkAbstractMapper3DData.cpp \
           IOData/CVtkAbstractMapperData.cpp \
           IOData/CVtkActorData.cpp \
           IOData/CVtkDataObject.cpp \
           IOData/CVtkDataSet.cpp \
           IOData/CVtkDataSetMapperData.cpp \
           IOData/CVtkImageData.cpp \
           IOData/CVtkLookupTableData.cpp \
           IOData/CVtkMapperData.cpp \
           IOData/CVtkPiecewiseFunctionData.cpp \
           IOData/CVtkPointSet.cpp \
           IOData/CVtkPolyData.cpp \
           IOData/CVtkPolyDataMapperData.cpp \
           IOData/CVtkRectilinearGrid.cpp \
           IOData/CVtkRendererData.cpp \
           IOData/CVtkRenderWindowData.cpp \
           IOData/CVtkScalarsToColorsData.cpp \
           IOData/CVtkStructuredGrid.cpp \
           IOData/CVtkStructuredPoints.cpp \
           IOData/CVtkTextureData.cpp \
           IOData/CVtkUniformGrid.cpp \
           IOData/CVtkUnstructuredGrid.cpp \
           IOData/CVtkObjectIOData.cpp \
           IOData/CVtkProp3DData.cpp \
           IOData/CVtkCameraData.cpp \
           IOData/CVtkImplicitFunctionData.cpp \
           IOData/CVtkPropertyData.cpp \
           IOData/CVtkAlgorithmData.cpp \
           IOData/CVtkLocatorData.cpp \
           IOData/CVtkAbstractPickerData.cpp \
           IOData/CVtkAbstractTransformData.cpp \
           IOData/CVtkImporterData.cpp \
           IOData/CVtkActor2DData.cpp \
           IOData/CVtkMapper2DData.cpp \
           IOData/CVtkInteractorObserverData.cpp \
           IOData/CVtkRenderWindowInteractorData.cpp \
           ControlData/CVtkObjectControlData.cpp 

FORMS +=   CRecordSettingsDialog.ui CPipelineProgressMonitor.ui            
RESOURCES += VTKSystem.qrc

# ShaderSupport stuff
INCLUDEPATH += ShaderSupport
DEPENDPATH  += ShaderSupport
HEADERS += ShaderSupport/DefineShaderDialog.h ShaderSupport/ShaderEditor.h
SOURCES += ShaderSupport/DefineShaderDialog.cpp ShaderSupport/ShaderEditor.cpp
FORMS   += ShaderSupport/DefineShaderDialog.ui

# vtkQtGraphicsViewRenderWindow implementation
HEADERS         += ../../3rdParty/vtkQtGraphicsViewRenderWindow/vtkQtGraphicsViewRenderWindow.h
SOURCES         += ../../3rdParty/vtkQtGraphicsViewRenderWindow/vtkQtGraphicsViewRenderWindow.cpp
INCLUDEPATH     += ../../3rdParty/vtkQtGraphicsViewRenderWindow/
DEPENDPATH      += ../../3rdParty/vtkQtGraphicsViewRenderWindow/

